// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBqrWvUT3tA-7Fmzz45mrCcJueLRSkds',
    appId: '1:1069598198937:android:4318fbb24f7b078e263c08',
    messagingSenderId: '1069598198937',
    projectId: 'partes-de-trabajo-571fb',
    storageBucket: 'partes-de-trabajo-571fb.appspot.com',
    androidClientId: '1069598198937-aq9gjbo3810ots2oogf04bdc96udhrfg.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJQhkGGPDKUusnCnUBAoY2uLAr2WhuHxE',
    appId: '1:1069598198937:ios:a6a4341b8869f22c263c08',
    messagingSenderId: '1069598198937',
    projectId: 'partes-de-trabajo-571fb',
    storageBucket: 'partes-de-trabajo-571fb.appspot.com',
    iosClientId: '1069598198937-vkdf9ctm8g2c8h3q06b5va0ao2tflej3.apps.googleusercontent.com',
    iosBundleId: 'com.instalacioneselectricasprie.partesdetrabajo',
  );
}
